/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bdguid;

/**
 *
 * @author Shaitan
 */
public class MainBDGui extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer MainBDGui
     */
    public MainBDGui() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Global_Panel = new javax.swing.JTabbedPane();
        Gestion_Panel = new javax.swing.JPanel();
        Internal_Gestion_Panel = new javax.swing.JTabbedPane();
        Internal_Reports_User_Security = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Report_Panel = new javax.swing.JPanel();
        Internal_Reports_Panel = new javax.swing.JTabbedPane();
        Internal_Reports_Panel_Employ_List = new javax.swing.JPanel();
        Generate_Employ_Table = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Employ_Table = new javax.swing.JTable();
        Internal_Reports_Panel_Schedule_Medical = new javax.swing.JPanel();
        Doctor_Name_Schedule_Label = new javax.swing.JLabel();
        Doctor_Month_Schedule_Labe = new javax.swing.JLabel();
        Doctor_Name_Schedule_Field = new javax.swing.JTextField();
        Generate_Schedule_Medical = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Schedule_Medical_Table = new javax.swing.JTable();
        Doctor_Month_Schedule_ComboBox = new javax.swing.JComboBox();
        Internal_Reports_Panel_Medical_Record = new javax.swing.JPanel();
        Medical_Record_IdPatient_Label = new javax.swing.JLabel();
        Generate_Medical_Record = new javax.swing.JButton();
        Medical_Record_IdPatient_Field = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Medical_Record_Table = new javax.swing.JTable();
        Internal_Reports_Panel_Dates = new javax.swing.JPanel();
        Generate_Count_Dates = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Count_Dates_Table = new javax.swing.JTable();
        Internal_Reports_Panel_Average_Costs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        Internal_Reports_User_Security.setName("Serch"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        jPanel1.setToolTipText("");

        jLabel11.setText("jLabel11");

        jTextField1.setText("jTextField1");

        jLabel12.setText("jLabel12");

        jTextField2.setText("jTextField2");

        jLabel13.setText("jLabel13");

        jTextField3.setText("jTextField3");

        jButton3.setText("jButton3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User", "Name", "ID", "Security Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(86, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update & Delete", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        jLabel14.setText("jLabel14");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User", "Name", "ID", "Security Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        jTextField4.setText("jTextField4");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(jButton5)
                        .addGap(70, 70, 70)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Create"));

        jLabel15.setText("jLabel15");

        jTextField5.setText("jTextField5");

        jLabel16.setText("jLabel16");

        jTextField6.setText("jTextField6");

        jLabel17.setText("jLabel17");

        jTextField7.setText("jTextField7");

        jButton6.setText("jButton6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(32, 32, 32)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel16)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel17)
                        .addGap(46, 46, 46)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Internal_Reports_User_SecurityLayout = new javax.swing.GroupLayout(Internal_Reports_User_Security);
        Internal_Reports_User_Security.setLayout(Internal_Reports_User_SecurityLayout);
        Internal_Reports_User_SecurityLayout.setHorizontalGroup(
            Internal_Reports_User_SecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Internal_Reports_User_SecurityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Internal_Reports_User_SecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Internal_Reports_User_SecurityLayout.setVerticalGroup(
            Internal_Reports_User_SecurityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Internal_Reports_User_SecurityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Internal_Gestion_Panel.addTab("User & Security", Internal_Reports_User_Security);
        Internal_Gestion_Panel.addTab("tab2", jPanel4);

        javax.swing.GroupLayout Gestion_PanelLayout = new javax.swing.GroupLayout(Gestion_Panel);
        Gestion_Panel.setLayout(Gestion_PanelLayout);
        Gestion_PanelLayout.setHorizontalGroup(
            Gestion_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Internal_Gestion_Panel)
        );
        Gestion_PanelLayout.setVerticalGroup(
            Gestion_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Internal_Gestion_Panel)
        );

        Global_Panel.addTab("GESTION", Gestion_Panel);

        Generate_Employ_Table.setText("Generate");

        Employ_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Charge", "Area"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Employ_Table);
        if (Employ_Table.getColumnModel().getColumnCount() > 0) {
            Employ_Table.getColumnModel().getColumn(0).setResizable(false);
            Employ_Table.getColumnModel().getColumn(1).setResizable(false);
            Employ_Table.getColumnModel().getColumn(2).setResizable(false);
            Employ_Table.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout Internal_Reports_Panel_Employ_ListLayout = new javax.swing.GroupLayout(Internal_Reports_Panel_Employ_List);
        Internal_Reports_Panel_Employ_List.setLayout(Internal_Reports_Panel_Employ_ListLayout);
        Internal_Reports_Panel_Employ_ListLayout.setHorizontalGroup(
            Internal_Reports_Panel_Employ_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Internal_Reports_Panel_Employ_ListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(Internal_Reports_Panel_Employ_ListLayout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(Generate_Employ_Table)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Internal_Reports_Panel_Employ_ListLayout.setVerticalGroup(
            Internal_Reports_Panel_Employ_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Internal_Reports_Panel_Employ_ListLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Generate_Employ_Table)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
        );

        Internal_Reports_Panel.addTab("Employs", Internal_Reports_Panel_Employ_List);

        Doctor_Name_Schedule_Label.setText("Doctor");

        Doctor_Month_Schedule_Labe.setText("Month");

        Doctor_Name_Schedule_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doctor_Name_Schedule_FieldActionPerformed(evt);
            }
        });

        Generate_Schedule_Medical.setText("Generate");

        Schedule_Medical_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Day", "Time", "ID Patient", "Patient Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Schedule_Medical_Table);
        if (Schedule_Medical_Table.getColumnModel().getColumnCount() > 0) {
            Schedule_Medical_Table.getColumnModel().getColumn(0).setResizable(false);
            Schedule_Medical_Table.getColumnModel().getColumn(1).setResizable(false);
            Schedule_Medical_Table.getColumnModel().getColumn(2).setResizable(false);
            Schedule_Medical_Table.getColumnModel().getColumn(3).setResizable(false);
        }

        Doctor_Month_Schedule_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jaunary", "Febrauary", "March", "April", "May", "June", "August", "September", "October", "November", "December" }));

        javax.swing.GroupLayout Internal_Reports_Panel_Schedule_MedicalLayout = new javax.swing.GroupLayout(Internal_Reports_Panel_Schedule_Medical);
        Internal_Reports_Panel_Schedule_Medical.setLayout(Internal_Reports_Panel_Schedule_MedicalLayout);
        Internal_Reports_Panel_Schedule_MedicalLayout.setHorizontalGroup(
            Internal_Reports_Panel_Schedule_MedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Internal_Reports_Panel_Schedule_MedicalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(Internal_Reports_Panel_Schedule_MedicalLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(Internal_Reports_Panel_Schedule_MedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Generate_Schedule_Medical)
                    .addGroup(Internal_Reports_Panel_Schedule_MedicalLayout.createSequentialGroup()
                        .addComponent(Doctor_Name_Schedule_Label)
                        .addGap(29, 29, 29)
                        .addComponent(Doctor_Name_Schedule_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Doctor_Month_Schedule_Labe)))
                .addGap(18, 18, 18)
                .addComponent(Doctor_Month_Schedule_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Internal_Reports_Panel_Schedule_MedicalLayout.setVerticalGroup(
            Internal_Reports_Panel_Schedule_MedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Internal_Reports_Panel_Schedule_MedicalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Internal_Reports_Panel_Schedule_MedicalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doctor_Name_Schedule_Label)
                    .addComponent(Doctor_Month_Schedule_Labe)
                    .addComponent(Doctor_Name_Schedule_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Doctor_Month_Schedule_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(Generate_Schedule_Medical)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );

        Internal_Reports_Panel.addTab("Schedule Medical", Internal_Reports_Panel_Schedule_Medical);

        Medical_Record_IdPatient_Label.setText("ID Patient");

        Generate_Medical_Record.setText("Generate");

        Medical_Record_IdPatient_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Medical_Record_IdPatient_FieldActionPerformed(evt);
            }
        });

        Medical_Record_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Date", "Id Doctor", "Doctor Name", "Cost", "Causes Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Medical_Record_Table);
        if (Medical_Record_Table.getColumnModel().getColumnCount() > 0) {
            Medical_Record_Table.getColumnModel().getColumn(0).setResizable(false);
            Medical_Record_Table.getColumnModel().getColumn(1).setResizable(false);
            Medical_Record_Table.getColumnModel().getColumn(2).setResizable(false);
            Medical_Record_Table.getColumnModel().getColumn(3).setResizable(false);
            Medical_Record_Table.getColumnModel().getColumn(4).setResizable(false);
            Medical_Record_Table.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout Internal_Reports_Panel_Medical_RecordLayout = new javax.swing.GroupLayout(Internal_Reports_Panel_Medical_Record);
        Internal_Reports_Panel_Medical_Record.setLayout(Internal_Reports_Panel_Medical_RecordLayout);
        Internal_Reports_Panel_Medical_RecordLayout.setHorizontalGroup(
            Internal_Reports_Panel_Medical_RecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Internal_Reports_Panel_Medical_RecordLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Medical_Record_IdPatient_Label)
                .addGap(18, 18, 18)
                .addComponent(Medical_Record_IdPatient_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addGroup(Internal_Reports_Panel_Medical_RecordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Internal_Reports_Panel_Medical_RecordLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(Generate_Medical_Record)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Internal_Reports_Panel_Medical_RecordLayout.setVerticalGroup(
            Internal_Reports_Panel_Medical_RecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Internal_Reports_Panel_Medical_RecordLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(Internal_Reports_Panel_Medical_RecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Medical_Record_IdPatient_Label)
                    .addComponent(Medical_Record_IdPatient_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Generate_Medical_Record)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );

        Internal_Reports_Panel.addTab("Medical Record", Internal_Reports_Panel_Medical_Record);

        Generate_Count_Dates.setText("Generate");

        Count_Dates_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Doctor", "Doctor Name", "Dates"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(Count_Dates_Table);
        if (Count_Dates_Table.getColumnModel().getColumnCount() > 0) {
            Count_Dates_Table.getColumnModel().getColumn(0).setResizable(false);
            Count_Dates_Table.getColumnModel().getColumn(1).setResizable(false);
            Count_Dates_Table.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout Internal_Reports_Panel_DatesLayout = new javax.swing.GroupLayout(Internal_Reports_Panel_Dates);
        Internal_Reports_Panel_Dates.setLayout(Internal_Reports_Panel_DatesLayout);
        Internal_Reports_Panel_DatesLayout.setHorizontalGroup(
            Internal_Reports_Panel_DatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Internal_Reports_Panel_DatesLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(Generate_Count_Dates)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Internal_Reports_Panel_DatesLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        Internal_Reports_Panel_DatesLayout.setVerticalGroup(
            Internal_Reports_Panel_DatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Internal_Reports_Panel_DatesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Generate_Count_Dates)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Internal_Reports_Panel.addTab("Dates", Internal_Reports_Panel_Dates);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Medicine");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Date");

        jButton1.setText("Generate");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Medicine");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Date");

        jButton2.setText("Generate");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Monthly Average");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Anual Average");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("---");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setText("---");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("---");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("---");

        javax.swing.GroupLayout Internal_Reports_Panel_Average_CostsLayout = new javax.swing.GroupLayout(Internal_Reports_Panel_Average_Costs);
        Internal_Reports_Panel_Average_Costs.setLayout(Internal_Reports_Panel_Average_CostsLayout);
        Internal_Reports_Panel_Average_CostsLayout.setHorizontalGroup(
            Internal_Reports_Panel_Average_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(Internal_Reports_Panel_Average_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addGap(176, 176, 176))
            .addGroup(Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(Internal_Reports_Panel_Average_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                .addGroup(Internal_Reports_Panel_Average_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel5))
                    .addGroup(Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Internal_Reports_Panel_Average_CostsLayout.setVerticalGroup(
            Internal_Reports_Panel_Average_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Internal_Reports_Panel_Average_CostsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(45, 45, 45)
                .addGroup(Internal_Reports_Panel_Average_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addGroup(Internal_Reports_Panel_Average_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(Internal_Reports_Panel_Average_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel3))
                .addGap(120, 120, 120)
                .addGroup(Internal_Reports_Panel_Average_CostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addGap(52, 52, 52)
                .addComponent(jButton2)
                .addContainerGap())
        );

        Internal_Reports_Panel.addTab("Average Costs", Internal_Reports_Panel_Average_Costs);

        javax.swing.GroupLayout Report_PanelLayout = new javax.swing.GroupLayout(Report_Panel);
        Report_Panel.setLayout(Report_PanelLayout);
        Report_PanelLayout.setHorizontalGroup(
            Report_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Internal_Reports_Panel)
        );
        Report_PanelLayout.setVerticalGroup(
            Report_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Internal_Reports_Panel)
        );

        Global_Panel.addTab("REPORTS", Report_Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Global_Panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Global_Panel)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Doctor_Name_Schedule_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doctor_Name_Schedule_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Doctor_Name_Schedule_FieldActionPerformed

    private void Medical_Record_IdPatient_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Medical_Record_IdPatient_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Medical_Record_IdPatient_FieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Count_Dates_Table;
    private javax.swing.JComboBox Doctor_Month_Schedule_ComboBox;
    private javax.swing.JLabel Doctor_Month_Schedule_Labe;
    private javax.swing.JTextField Doctor_Name_Schedule_Field;
    private javax.swing.JLabel Doctor_Name_Schedule_Label;
    private javax.swing.JTable Employ_Table;
    private javax.swing.JButton Generate_Count_Dates;
    private javax.swing.JButton Generate_Employ_Table;
    private javax.swing.JButton Generate_Medical_Record;
    private javax.swing.JButton Generate_Schedule_Medical;
    private javax.swing.JPanel Gestion_Panel;
    private javax.swing.JTabbedPane Global_Panel;
    private javax.swing.JTabbedPane Internal_Gestion_Panel;
    private javax.swing.JTabbedPane Internal_Reports_Panel;
    private javax.swing.JPanel Internal_Reports_Panel_Average_Costs;
    private javax.swing.JPanel Internal_Reports_Panel_Dates;
    private javax.swing.JPanel Internal_Reports_Panel_Employ_List;
    private javax.swing.JPanel Internal_Reports_Panel_Medical_Record;
    private javax.swing.JPanel Internal_Reports_Panel_Schedule_Medical;
    private javax.swing.JPanel Internal_Reports_User_Security;
    private javax.swing.JTextField Medical_Record_IdPatient_Field;
    private javax.swing.JLabel Medical_Record_IdPatient_Label;
    private javax.swing.JTable Medical_Record_Table;
    private javax.swing.JPanel Report_Panel;
    private javax.swing.JTable Schedule_Medical_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
